# Generated by Django 4.2.7 on 2024-12-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Total_person',
            new_name='Total_Person',
        ),
    ]
