# Generated by Django 4.2.7 on 2024-12-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_rename_total_person_booktable_total_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Total_Person',
            new_name='Total_person',
        ),
    ]
