# Generated by Django 5.1.4 on 2025-01-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
